version: '2'
services:
    www:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile

    php:
        build:
            context: .
            dockerfile: docker/php7/Dockerfile

    db:
        image: mysql:5.7
