version: '2'
services:
    www:
        extends:
            file: docker-compose.base.yml
            service: www
        ports:
            - "8080:80"
        volumes:
            - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
            - "./:/usr/src/app"

    php:
        extends:
            file: docker-compose.base.yml
            service: php
        volumes:
            - "./:/usr/src/app"
        environment:
            - "APP_ENV=local"
            - "APP_DEBUG=true"
            - "DB_HOST=db"
            - "DB_DATABASE=vanilla_app"
            - "DB_USERNAME=vanilla"
            - "DB_PASSWORD=someRandomString"

    db:
        extends:
            file: docker-compose.base.yml
            service: db
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=123qwe"
            - "MYSQL_DATABASE=vanilla_app"
            - "MYSQL_USER=vanilla"
            - "MYSQL_PASSWORD=someRandomString"
